fix failing tests caused by `vitest.spyOn`
TypeError: Cannot spy on export "<method_name>". Module namespace is not configurable in ESM. See: https://vitest.dev/guide/browser/#limitations